export const FETCH_PHONES_PENDING = "FETCH_PHONES_PENDING";
export const FETCH_PHONES_SUCCESS = "FETCH_PHONES_SUCCESS";
export const FETCH_PHONES_FAILED = "FETCH_PHONES_FAILED";

export const FETCH_ONE_PHONES_PENDING = "FETCH_ONE_PHONES_PENDING";
export const FETCH_ONE_PHONES_SUCCESS = "FETCH_ONE_PHONES_SUCCESS";
export const FETCH_ONE_PHONES_FAILED = "FETCH_ONE_PHONES_FAILED";

export const TOOGLE_CATALOGUE_VIEW = "TOOGLE_CATALOGUE_VIEW";

export const SET_SORT_AZ = "SET_SORT_AZ";
export const SET_SORT_ZA = "SET_SORT_ZA";
export const SET_SORT_19 = "SET_SORT_19";
export const SET_SORT_91 = "SET_SORT_91";
