export const FETCH_PHONES_PENDING = "FETCH_PHONES_PENDING";
export const FETCH_PHONES_SUCCESS = "FETCH_PHONES_SUCCESS";
export const FETCH_PHONES_FAILED = "FETCH_PHONES_FAILED";

export const FETCH_ONE_PHONES_PENDING = "FETCH_ONE_PHONES_PENDING";
export const FETCH_ONE_PHONES_SUCCESS = "FETCH_ONE_PHONES_SUCCESS";
export const FETCH_ONE_PHONES_FAILED = "FETCH_ONE_PHONES_FAILED";
